#!/bin/sh

# chkconfig: 2345 99 01
# description: SoftEther VPN Server

DAEMON=/usr/bin/vpnserver
LOCK=/var/lock/vpnserver

test -x $DAEMON || exit 0
case "$1" in
start)
    $DAEMON start
    touch $LOCK
    ;;

stop)
    $DAEMON stop
    rm $LOCK
    ;;

restart)
    $DAEMON stop
    sleep 3
    $DAEMON start
    ;;

status)
    if [ -e $LOCK ]; then
        echo "vpnserver is running."
    else
        echo "vpnserver is not running."
    fi
    ;;

*)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
esac

exit 0

